export const COLORS = {
    COLOR_TRANSPARENT: 'transparent',
    COLOR_COD_GRAY: '#1C1C1C',
    COLOR_SILVER_CHALICE: '#AAAAAA',
    COLOR_SILVER: '#BBBBBB',
    COLOR_MERCURY: '#ececece6',
    COLOR_WHITE: '#FFFFFF',
    COLOR_SUCCESS: '#25CB55',
    COLOR_DANGER: '#D0021B',
};